### ISSUE TITLE
Question: How to add and use a .coveragerc file ?

### ISSUE THREAD

**Issue by RaccoonForever** [databrickslabs/dbx#268]
Hello guys,

I'm trying to use your tool for Integration Tests on Databricks. 
Unit test are done locally but I need to test some functions that use Databricks hive metastore etc...

I've no trouble running tests using dbx ! (Thanks for that)
But now I'm trying to add some coverage programmatically using your template !

My deployment.yml:

![image](https://user-images.githubusercontent.com/4057852/171024350-c08831ab-ebac-4346-8b67-9612bf374c05.png)

My code:
![image](https://user-images.githubusercontent.com/4057852/171024420-c1f6f6bb-cc8c-4423-86be-c45eb6037b39.png)

Everything is launched, but it does not seem to access the file. I've tried others path etc...

Could you help me reach the file from the code on Databricks ?

I could define the config directly in the class definition of Coverage, but I'd prefer to work with a config file which will be cleaner and more modular.

Thanks

**Comment by teaVeloper** [comment]
I use `pytest` (altough with an entrypoint script as a wrapper) and the `pytest-cov` plugin, all defined in a `pyproject.toml`.
Tough a bit different setup, my solution should (hopefully) work for you.

As far as I see, you include the config-file as `fuse` link as parameter in your `deployment.yml`.
Within `__main__` you call a `local` version of `.coveragerc`. But there is no necessary link between your local path and your entrypoint-files location. (e.g. `python /path/to/file.py`, vs. `python file.py`)
You could parametrize the `.coveragerc` location, either using a more 'sophisticated` cli (beware click and thus typer have a bug on databricks [because of ipython]( https://stackoverflow.com/questions/52740295/how-to-not-exit-a-click-cli) or plain old `sys.args` and just give the `fuse` link as parameter.

here my example:
```deployment.yaml
... omitted ...
      - name: test-task
        <<: *basic-static-cluster
        spark_python_task:
          python_file: file://tests/run_tests.py
          parameters: [--conf-file, "file:fuse://pyproject.toml"] # with sys.arg of course no named parameter
```
I will leave out the `entrypoint` file, as mine uses typer and thus the cli is just a function signature. But i guess you get the point.

**Comment by RaccoonForever** [comment]
Thanks, I'll try this for my own case !

Using my files as parameters in the deployment.yml make them uploaded on the Databricks cluster, but I couldn't access to it. I am almost sure that we could do something :)

I'll keep you in touch :)

**Comment by RaccoonForever** [comment]
Ok, it works :) !

I'm just trying to make the 'source' configuration work (to be used with relative_paths) but no success.
It might again be a problem of path not found, and I guess that 'source' doesn't support glob.
