### ISSUE TITLE
DBX R Support

### ISSUE THREAD

**Issue by BKDaugherty** [databrickslabs/dbx#290]
## Does DBX support R projects?

My company is trying to decide whether we should use `dbx`, `databricks-connect` or some other hacky solution for interactively running our R code from our own ide against databricks clusters. However, as I was reading through the [docs](https://docs.databricks.com/dev-tools/dbx.html) here, I noticed that there wasn't anything about R, only Python, Java and Scala.

Is there planned work for docs around how I would "Create a minimal dbx project for R"? With `databricks-connect` we would simply use it and connect with `sparklyr` but it seems like support for that is on the out, and `dbx` is the new shiny hotness.

Sorry in advance for my ignorance if this is the wrong place to ask this question!

**Comment by renardeinside** [comment]
hi @BKDaugherty , 

dbx currently supports the following in terms of R:
- dbx deploy
- dbx launch

Yet we don't support dbx execute (interactive execution from local IDE). I was considering this use-case as something which doesn't happen often since I assume that R developers prefer DB Connect or Rstudio directly on the interactive clusters.

To sum up - you can use DB Connect together with dbx, DB connect will provide you interactive development experience, whilst dbx will be responsible for CI/CD and jobs deployment. 

In future releases we potentially will add a project template for R (feel free to contribute one!), and implement execute support for it.

**Comment by BKDaugherty** [comment]
> To sum up - you can use DB Connect together with dbx, DB connect will provide you interactive development experience, whilst dbx will be responsible for CI/CD and jobs deployment.

Sweet! Thanks for the response! I think we will go with this for now, and if `dbx` fits our usecase will look to add a project template and support where we can. Thanks again!
