### ISSUE TITLE
Example does not work when executing using an existing cluster

### ISSUE THREAD

**Issue by seanlindo** [databrickslabs/dbx#302]
## Expected Behavior
`dbx execute --cluster-id=<CLUSTER_REDACTED> --job=cicd-sample-project-sample-etl-2.0 --no-package` should work

## Current Behavior
`ModuleNotFoundError: No module named 'cicd_sample_project'`

## Steps to Reproduce (for bugs)
* Launch a cluster running 10.4 LTS
* Install dbx 0.6.2
* Execute db init using the default options. Run `dbx configure` if necessary so your token comes through
* run the command above in a Pipenv environment with Python 3.8.10 installed

## Your Environment

* dbx version used: 0.6.2
* Databricks Runtime version: 10.4 LTS

**Comment by seanlindo** [comment]
Seems to work given the following:

1. The example relies on `pyyaml`. You will need to run `pipenv install pyyaml`
2. Generate a requirements file: `pipenv run pip freeze > requirements.txt`
3. The entire application will need to be packaged and executed: `dbx execute --cluster-id=<CLUSTER_REDACTED> --job=cicd-sample-project-sample-etl-2.0`

**Comment by ptabandzelic** [comment]
> 

Any update?I have same issue.

**Comment by renardeinside** [comment]
hi @seanlindo and @ptabandzelic 

maybe there is a doc issue, but it explicitly states the [following](https://dbx.readthedocs.io/en/latest/README.html#limitations):
> `dbx execute` can only be used on clusters with Databricks **ML** Runtime 7.X or higher.

this is because we expect DBR ML to provide specific libraries (including pyyaml). If you want to use a non-ML DBR, then you need to add the pyyaml package and pass it in the requirements.txt as you've mentioned above. 

Does that cover your question? Let me know if we shall add this limitation somewhere to make it more visible.

**Comment by renardeinside** [comment]
Closed as no comments for 2 weeks. 
@seanlindo please let me know if a follow up is required.
