### ISSUE TITLE
Deploy without permission to install on cluster

### ISSUE THREAD

**Issue by ptabandzelic** [databrickslabs/dbx#319]
Is it possible to dbx deploy without having permission to install on cluster since everything is installed as python package?

**Comment by renardeinside** [comment]
hi @ptabandzelic , 
could you please specify - do you want to to `dbx deploy` with interactive cluster (`existing_cluster_{id/name}`) or on a job cluster?

**Comment by renardeinside** [comment]
since you're using:
> existing_cluster_id 
it's an **interactive** (also called all-purpose) cluster - it's **not** a job cluster. 
In general we don't recommend running automated jobs on the interactive clusters, please read the details [here](https://dbx.readthedocs.io/en/latest/templates/python_basic.html#running-your-code-on-the-databricks-clusters).

**Comment by ptabandzelic** [comment]
> 

But when i use dbx execute on existing cluster, its working, run is completed.When dbx deployed i got error that i cant install anything on cluster.
Interactive(all-purpose) clusters are the ones that we have defined all the time?Job clusters are the one created just for a job run?

**Comment by renardeinside** [comment]
> But when i use dbx execute on existing cluster, its working, run is completed.When dbx deployed i got error that i cant install anything on cluster.

this is because dbx execute uses a different interface for library installation - it's called context-based library installation and it's incompatible with job-like launches. 

> Interactive(all-purpose) clusters are the ones that we have defined all the time?Job clusters are the one created just for a job run?

yes, exactly. you can find more on the difference between all-purpose and job clusters [here](https://docs.databricks.com/clusters/index.html#:~:text=Databricks%20makes%20a%20distinction%20between,%2C%20CLI%2C%20or%20REST%20API.) and [here](https://community.databricks.com/s/question/0D53f00001HKHjOCAX/whats-the-difference-between-interactive-clusters-and-job-cluster).

**Comment by ptabandzelic** [comment]
thanks, liked your talks on youtube a lot.
