### ISSUE TITLE
timeout_seconds Parameter not applied at dbx execute time

### ISSUE THREAD

**Issue by srghat** [databrickslabs/dbx#360]
## Expected Behavior
timeout_seconds: 100 parameter set up from YAML needs to propagate to the dbx execute call and maintain connection for at least timeout_seconds since a last locking Python operation is executed.

## Current Behavior
Timeout currently is unknown, but estimated at around 30-45s.

## Steps to Reproduce (for bugs)
time.sleep(250) in a Python job code, and timeout_seconds: 100 in a job yml config

## Context
NA

## Your Environment
* dbx version used:0.6.8
* Databricks Runtime version: 10.1

**Comment by renardeinside** [comment]
hi @srghat , 
Could you please provide the relevant part of job configuration from your `conf/deployment.yml`?

**Comment by renardeinside** [comment]
I've reproduced this behaviour. 

Reason is the following - `timeout_seconds` is being calculated form the moment of the job start. 
Since some time is needed to start the VMs, the countdown in Python application starts later which leads to the interruption. 

Resolution is the following - add approx. 3 minutes to the timeout_seconds as a safety measure for the  time which is spent on warming up the VMs.
