### ISSUE TITLE
How should i go about installing some other wheel file.

### ISSUE THREAD

**Issue by ptabandzelic** [databrickslabs/dbx#365]
Hey, how to install inside task an additional wheel file?Should i put it in conf/deployment.yaml under libraries section.
Should i put it in requirements.Where should wheel file live?
Thanks

**Comment by renardeinside** [comment]
hi @ptabandzelic , 
there are multiple options:

1. you can put this wheel file into your private pypi repository (e.g. Nexus, JFrog, Azure Artifacts, AWS Code Artifact). Then reference[ this dependency in your `setup.py` file and add a custom pypi repo into it. ](https://stackoverflow.com/questions/18828805/how-can-i-install-packages-hosted-in-a-private-pypi-using-setup-py).
This is the most recommended from the DevOps perspective  approach since you got proper versioning for this .whl file. This approach would work for `dbx deploy` and `dbx execute`. 

2. Another option is to add this file to the libraries dependency directly via the following syntax:

```
# conf/deployment.yml

... 
new_cluster:
  libraries: 
   - pypi: 
       package: file://path/to/your/local/file
```
In this case file will be picked up automatically during `dbx deploy`, uploaded to the dbfs and used in library references. Please note that for interactive clusters you'll need to install this dependency separately via UI or via API.
