### ISSUE TITLE
Is it possible to use dbx to execute Spark code line by line

### ISSUE THREAD

**Issue by mckwxp** [databrickslabs/dbx#390]
I am coming from databricks-connect where I use it to develop and run interactive Jupyter notebooks on my local machine and execute the Spark code remotely. I am aware that databricks is stopping development of databricks-connect and so I am looking to migrate to dbx. However I am not sure if my use case is covered by dbx, particularly because I read in dbx's limitations section, there is no interactive debugging capabilities and I was actually told to use databricks-connect for this purpose.

So can I just confirm that dbx is currently unable to execute interactive notebooks just like how databricks-connect works?

**Comment by renardeinside** [comment]
hi @mckwxp , 

Your understanding is correct - at the moment dbx doesn't support interactive line-by-line execution. If you're looking for such capabilities please reach out to your account SA.

**Comment by JeremyDemlow** [comment]
Are we to assume that this isn't a part of the work track anymore there is so much value of being able to experiment and document in the preference of a working environment like Jupyter

An example is a huge increase in productivity from things like NBDEV that will allow for extremely good documentation as things become very complex pushing work flows to databricks. 

Is there a ticket anywhere that is going to re-open something like this because it's a huge use case as using DB UI is not something that has much appeal unless it works for use cases but really is a completely different dev set up

**Comment by renardeinside** [comment]
hi @JeremyDemlow , 
this functionality won't be part of `dbx`, rather then another product - [Spark Connect](https://www.databricks.com/blog/2022/07/07/introducing-spark-connect-the-power-of-apache-spark-everywhere.html). 
Please reach out to your account SA for details.

**Comment by Jeremy-Demlow** [comment]
Sounds good means the time to really move into databricks is on that time line really looking forward to using it some day soon 👍🏻
