### ISSUE TITLE
[DOCS] docs on libraries and dependency management

### ISSUE THREAD

**Issue by renardeinside** [databrickslabs/dbx#424]
approx. content:

- Python package dependency management
- Maven/jar dependency management

**Comment by pspeter** [comment]
Hi @renardeinside,

I use pip-tools to pin my project dependencies and separately pin my test/lint/etc. dependencies. I don't understand how I would currently (in dbx 0.7.4) use these different dependency files (requirements.txt, requirements-test.txt...) with different dbx deployments/workflows. Right now `dbx deploy` still has the `--requirements-file` flag, but that only supports one file and, moreover, is now deprecated. But without that, I don't see how I could run different workflows with different requirements except by shoving *all* requirements from all workflows into the setup.py *and* pinning them there, which is really not ideal.

To give a concrete example, I have an integration-test workflow, which depends on `pytest` and some other dependencies. I don't want to add these to setup.py just for this test workflow.

Any help is appreciated, maybe I just missed something in the current documentation. If not, maybe you can use this as input for the planned documentation, which is why I didn't open a new issue. But currently I just found this note for the --requirements-file option: `Please note that this option is deprecated. We strongly recommend to use standard 🐍 Python packaging for dependency management.`, which is confusing, since requirement files have been the standard way to pin dependencies for a really long time.

Thanks ahead!

PS: I also noticed you can add dependencies to the deployment.yml file in the "libraries" section, but that is more tedious to maintain than requirement files with pip-tools, and it's only mentioned once in the docs here: https://dbx.readthedocs.io/en/latest/guides/python/python_quickstart/?h=libraries#deployment-configuration.

**Comment by DanMan259** [comment]
Any updates on this ^

**Comment by renardeinside** [comment]
hi @pspeter  and @DanMan259 , 
please check the latest docs update and specifically [this page](https://dbx.readthedocs.io/en/latest/guides/general/dependency_management/).

It explains most of the aspects of dependency management, as well as covers non-python library installs topics. 
Please feel free to open a new issue if required.
