### ISSUE TITLE
Specifying dependencies when running notebook tasks from git source

### ISSUE THREAD

**Issue by danielwillemsen** [databrickslabs/dbx#439]
I'm curious about the recommended way of specifying dependencies when deploying a job with notebook tasks using a git source.

**Context:**
Before dbx version 0.7, our approach for deploying a notebook based job from a CICD pipeline was as follows:

- In our deployment.yml, we specify a git source for the notebooks to be used.

- In the CI/CD pipeline the following steps were done:
    1. Export our poetry dependencies to a requirements.txt 
    2. Deploy the job using `dbx deploy --no-package --no-rebuild --requirements-file=requirement.txt`

The reason we did it this way was mainly because we like:
- The traceability provided by using the git source directly.
- The ease of not having people have to worry about packaging, instead; the notebook files could always immediately find the library to import from as it was located in the same repo.

**Problem:** As of dbx version 0.7, the --requirements-file option is deprecated, so this approach no longer seems a good idea.
Two alternatives I see are:
- Stop using notebook tasks and instead use python wheel tasks. Downside: we loose the ability to use the git source in our deployment.
- Continue using the current approach. Downside: we are using deprecated functionality.

**Questions:** 
1. What would your recommendation be regarding the best practice of approaching this? 
2. Are there any ways to keep using the git source with either poetry or requirements.txt for dependencies, but not using any deprecated functionalities?

* dbx version used: 0.7.2
* Databricks Runtime version:

**Comment by renardeinside** [comment]
hi @danielwillemsen , 
Instead of using requirements.txt do the following:

1. Specify your dependencies to the `setup.py` instead of using a separate requirements file. 
2. In your deployment command, omit the `--no-package --no-rebuild` sections. 
3. This will automatically prepare your package and add dependencies to the metadata of the package. 
4. Package will be automatically added to the job and installed with it's dependencies on the cluster during job run.
