### ISSUE TITLE
[BUG] version package uploaded

### ISSUE THREAD

**Issue by andompesta** [databrickslabs/dbx#49]
## Expected Behavior
If I generate a different version of my package to deploy. For example, if I move from version 0.0.1 to 0.0.2 I expect to deploy on the cluster version 0.0.2, not 0.0.1.
This work only if I manually delete from the `dist` folder the wheel package relative to version 0.0.1.

## Current Behavior
If I generate 2 wheel packages for different version of the same library, the old version is pushed to the cluster.

## Steps to Reproduce (for bugs)
1) deploy a package with version 0.0.1 using ``dbx deploy``
2) modify the version in the ``__init__.py`` file
3) execute ``dbx deploy`` once again, but the old version is still pushed

## Your Environment

* dbx version used: 0.1.3
* Databricks Runtime version: 7.5 ML

**Comment by allebacco** [comment]
This is probably due to the [`get_package_file()`](https://github.com/databrickslabs/dbx/blob/b1121387ee57f15f925588c88f7abe35e192b394/dbx/utils/common.py#L256) function that returns only the first wheel file in the `dist` folder.

So it seems that only a single wheel can be deployed at a time. The best approach is to always cleanup the `dist` folder before any deploy.

**Comment by renardeinside** [comment]
We need to add version-based sorting to the`get_package_file`. Let's include this into 1.0.4, fix shall be quite easy.

**Comment by renardeinside** [comment]
hi @andompesta , thanks a lot for raising the issue - I've fixed it in #56 , will be released in 0.1.4
