### ISSUE TITLE
Cluster creation when launching from assets

### ISSUE THREAD

**Issue by goldstein0101** [databrickslabs/dbx#608]
Why when launching workflow from assets, it creates cluster for each separate task?

**Comment by renardeinside** [comment]
Assets-based launch uses RunSubmit API [that unfortunately doesn't support sharing job clusters](https://dbx.readthedocs.io/en/latest/features/assets/?h=cluster+reuse#failsafe-behaviour-for-shared-job-clusters) (it's a limitation of the platform, not of dbx). 

Please use[ instance pools](https://docs.databricks.com/clusters/instance-pools/index.html) for such cases, they can significantly speedup the startup time. 
Also, since assets-based launch is mostly a technique used in development loops, it shouldn't affect your CI that much. 

I wouldn't recommend using asset-based launch in production though, there you definitely should create proper job objects with normal dbx deploy and launch. Read more on the difference [here](https://dbx.readthedocs.io/en/latest/concepts/cluster_types/#job-clusters).

**Comment by goldstein0101** [comment]
The problem is for production, i have to run ML task for different parameters, and i dont want to update workflow each time just to update different parameters. I think that makes sense.
What would your approach be?

**Comment by renardeinside** [comment]
> The problem is for production, i have to run ML task for different parameters, and i dont want to update workflow each time just to update different parameters. I think that makes sense.
What would your approach be?

I'm not sure if you're using `dbx` for it's purpose here, the pattern seems unusual.
 
You don't need to make it an engine for parameterized trials, and there is no need to create many jobs for that. 
Instead, create a single job and simply use the Hyperopt to train ML models with different parameter sets inside one job. It's way more scalable, controllable and clear from architecture perspective.

Check [this example](https://www.databricks.com/notebooks/churn/4-hyperparameter-tuning.html) and [this blogpost](https://www.databricks.com/blog/2021/04/15/how-not-to-tune-your-model-with-hyperopt.html) for explanation.

Does this pattern makes sense, our you have a different use-case?

**Comment by goldstein0101** [comment]
Well my production usecase, for example uses different set of features(dataset) depending on parameter, and based on that its a different set of input and outputs of tasks, but for each parameter its a same code logic.

**Comment by goldstein0101** [comment]
But i see your point, those params should be included in task and just loop over those
