### ISSUE TITLE
Resources already exsits

### ISSUE THREAD

**Issue by goldstein0101** [databrickslabs/dbx#613]
```
HTTPError: 400 Client Error: Bad Request for url: https://aaws-aawsdatabrickspoc.cloud.databricks.com/api/2.0/workspace/mkdirs
 Response from server: 
 { 'error_code': 'RESOURCE_ALREADY_EXISTS',
  'message': 'usecase_namealready exists and it is not a folder'}
```
Any idea about this reason? It happens when i just to redeploy usecase.

**Comment by renardeinside** [comment]
Hi @goldstein0101 , 
Please re-create the issue in a proper format (which is requested when you create the issue). 

This format is there not because we like bureaucracy, but because we need proper and clear understanding of the context - with traceback and versions, to avoid providing misleading guidance.
