### ISSUE TITLE
Launch deployed workflow multiple times

### ISSUE THREAD

**Issue by bensolom** [databrickslabs/dbx#684]
## Expected Behavior
Run deployed workflow multiple times with launch command (or another dbx alternative),
deploying the workflow only once.

## Current Behavior
After deploying job with
`dbx deploy
`
The workflow gets MLflow tag dbx_action_type='deployed'.
Then, running launch
`dbx launch <workflow_name>
`
The tag is changed to dbx_action_type='launch' and
the job cannot be running again with the launch command.

Exception: 
In the second run, I get the message:
```
No deployments provided per given set of filters:
    tags.dbx_environment = 'test' and tags.dbx_status = 'SUCCESS' and tags.dbx_action_type = 'deploy' and tags.dbx_branch_name = 'dbx'
To verify current status of deployments please check experiment UI in workspace dir: <dir>
```

## Steps to Reproduce (for bugs)
```
dbx deploy
dbx launch <workflow_name>
dbx launch <workflow_name>
```

## Notes
currently I have been able to run the deployed workflow with databricks CLI with
`databricks jobs run-now --job-id <jobid>
`
but I still wish to know why it isn't possible with dbx launch

* dbx version used: 0.8.7
* Databricks Runtime version: 0.17.4

Thank you
Ben

**Comment by nididpi** [comment]
I can confirm this issue. I believe it is coming from this PR  [#531](https://github.com/databrickslabs/dbx/pull/531)

what happened is, in the function of 
log_launch_info(additional_tags: Dict[str, Any], dbx_status, environment_name, branch_name)

it will update the tags.dbx_action_type = 'deploy' to 'launch', and if you run launch again, since it will look for a 'deploy' tag, it will fail.

**Comment by diederikperdok** [comment]
I can confirm this issue. If you deploy multiple workflows it is even worse: you can launch one of them once, and then all subsequent launches of any workflow will fail.

There used to be separate MLflow runs for deployment and launching; now the launch run updates the original run.

This does indeed seems to be caused by PR #531 so I'm going to try rolling back to v0.7.6 and see if that fixes the problem.

**Comment by diederikperdok** [comment]
Rolling back to v0.7.6 does indeed resolve this particular issue, in case anyone urgently needs a workaround
