### ISSUE TITLE
get_dbutils(): please note that this function is used in mocking by its name

### ISSUE THREAD

**Issue by panoptikum** [databrickslabs/dbx#723]
Hi guys,

Thank you so much for your work. It helps me a lot to setup good reproduicble jobs.

I want to fully understand your basic template and I am thinking about how you mock or initialize get_dbutils().

What does the comment "please note that this function is used in mocking by its name" mean? And what does the command "# noqa" after some lines stand for?

Thank you for your response.

**Comment by renardeinside** [comment]
hi @panoptikum , 
Thanks a lot for your kind words. 


Regarding your questions:

**1. Why `# noqa` comment used and what it means?** 

`# noqa` is a [comment](https://flake8.pycqa.org/en/latest/user/violations.html#in-line-ignoring-errors) that is recognised by `flake8`, a standard Python linting utility, used under the hood by IDEs like VS Code (and this is also recognized in Pycharm). Specifically for the code of the common.py, it suppresses the import-not-found warning. Since DBUtils are only available inside the Databricks environment and you don't have them locally, it will always raise a warning during local coding. To avoid it, we introduce this comment to suppress it. 
Same logic applies to some other lines among the common code.

**2.  What does the comment "please note that this function is used in mocking by its name" mean?**

`get_dbutils` is used by it's name in the `tests` appliance that is generated by the template:

```python

# --snip--

@pytest.fixture(scope="session", autouse=True)
def dbutils_fixture() -> Iterator[None]:
    """
    This fixture patches the `get_dbutils` function.
    Please note that patch is applied on a string name of the function.
    If you change the name or location of it, patching won't work.
    :return:
    """
    logging.info("Patching the DBUtils object")
    with patch("{project_name}.common.get_dbutils", lambda _: DBUtilsFixture()):
        yield
    logging.info("Test session finished, patching completed")
```

As you can see, the `patch` line is using the function name to mock the behaviour of DBUtils locally. If you change the name of the function without changing it in this test block, your tests will stop working properly in the local environment. Therefore we introduce a comment with a precaution.

Hope this helps. 🙌

**Comment by panoptikum** [comment]
Hi @renardeinside ,

It did help a lot. Thanks again.

I haven't had the time for a while to further dig into testing with dbx, but this week I had some time. We follow a notebook-based approach and I am not using a class at the moment to initalize the job, but it's a bit hard to mock things locally. For now it would already help me a lot, if you can give an example how I would use the patched dbutils in an actual test scenario.

```
@pytest.fixture(scope="session", autouse=True)
def dbutils_fixture() -> Iterator[None]:
    """
    This fixture patches the `get_dbutils` function.
    Please note that patch is applied on a string name of the function.
    If you change the name or location of it, patching won't work.
    :return:
    """
    logging.info("Patching the DBUtils object")
    with patch("common.get_dbutils", lambda _: DBUtilsFixture()):
        yield
    logging.info("Test session finished, patching completed")
```

I think the patch works in general as I have added the following to my `pyproject.toml`:
```
[tool.pytest.ini_options]
pythonpath = [
  "src"
]
```

but I get a `None` type nevertheless, if I use dbutils_fixture in a test like this:

```
import pytest

def test_spark_app(spark, dbutils_fixture):
    print(dbutils_fixture)
    spark.sql("SELECT current_user as USERNAME")
    assert spark.conf.get("spark.databricks.clusterUsageTags.clusterOwnerOrgId") == "mock_workspace_id"
```

What am I doing wrong and misunderstand? Bear with me please, if it's something simple. I am a bit new to this kind of mocking and testing.

Thanks and happy day!
