### ISSUE TITLE
[ISSUE] Honoring provided job names when deploying to databricks

### ISSUE THREAD

**Issue by max-mayrhofer** [databrickslabs/dbx#88]
## Expected Behavior

In the deployment.json/yaml file, the job name for each job is specified. On deploying to databricks, the expectation is that a job with the same name is deployed, and overwritten if necessary.

## Current Behavior

Currently, dbx deploy creates a new job with a name corresponding to the full path of the artifact directory and a UUID. This creates a large number of hard-to-differentiate entries.

![image](https://user-images.githubusercontent.com/12987411/136170548-6550e2c4-df14-459f-9818-d81ab32fb511.png)

## Steps to Reproduce (for bugs)

`dbx deploy --environment xyz --deployment-file conf/deployment.yaml`

## Your Environment

* dbx version used: 0.2.0
* Databricks Runtime version: N/A

**Comment by renardeinside** [comment]
hi @max-mayrhofer , 
it seems to me that the issue is that the local path is getting referenced incorrectly. 
Could you please try the strict path adjusting functionality as described [here](https://dbx.readthedocs.io/en/latest/path_adjustment.html)?

**Comment by max-mayrhofer** [comment]
That worked!! Thank you so much!! Weird though that it would have happened like that. Why would this be the reason that the job name is what it is?

**Comment by renardeinside** [comment]
oh, it's a deep issue, but I'll try to explain. 

The non-strict path adjustment logic simply walks through all values in the deployment configuration and if the value is recognized as a path, it will be replaced with dbfs:/... prefix. Since you probably have a folder that is equal to the job name, it thinks it's a path which needs adjustment. 
With strict path adjustment, it only works with strings that have file:// prefix. 

good that it was resolved. please feel free to reopen the issue if needed :)
